// generated by unplugin-vue-components
// We suggest you to commit this file into source control
// Read more: https://github.com/vuejs/vue-next/pull/3399

declare module 'vue' {
  export interface GlobalComponents {
    NButton: typeof import('naive-ui')['NButton']
    NConfigProvider: typeof import('naive-ui')['NConfigProvider']
    NDropdown: typeof import('naive-ui')['NDropdown']
    NGlobalStyle: typeof import('naive-ui')['NGlobalStyle']
    NIcon: typeof import('naive-ui')['NIcon']
    NLayout: typeof import('naive-ui')['NLayout']
    NLayoutContent: typeof import('naive-ui')['NLayoutContent']
    NLayoutFooter: typeof import('naive-ui')['NLayoutFooter']
    NLayoutHeader: typeof import('naive-ui')['NLayoutHeader']
    NLayoutSider: typeof import('naive-ui')['NLayoutSider']
    NSpace: typeof import('naive-ui')['NSpace']
    PageNotFound: typeof import('./src/components/PageNotFound.vue')['default']
    SwitchLocale: typeof import('./src/components/Button/SwitchLocale.vue')['default']
    SwitchTheme: typeof import('./src/components/Button/SwitchTheme.vue')['default']
    SwitchThemeCopy: typeof import('./src/components/Button/SwitchTheme-copy.vue')['default']
    VueDash: typeof import('./src/components/VueDash.vue')['default']
  }
}

export { }
